Task 1
GlebMakhankov/webix-jet pull request #1
Opened 2021-10-02 21:51 UTC by GlebMakhankov

Task 1

2021-10-03 19:46 UTC, HelgaListopad requested changes
Всё работает, но лаконичный на первый взгляд стиль кода может приносить по мере расширения приложения кучу страданий.
Я не советую выносить за пределы класса конфигурации UI компонентов как переменные и создавать ситуации, когда ID (как глобальные, так и локальные для класса) объявлены/используются в разных файлах.

Пример глобальных айдишек в разных файлах
<details><summary>multiview + menu</summary>

![image](https://user-images.githubusercontent.com/7587383/135768136-2089f21a-330d-402b-971f-85e16e7ca3d5.png)
</details>

Пример трудно считываемого кода (+ глобальные айдишки)
<details><summary>таббар и мультивью + parse непонятно куда</summary>

![image](https://user-images.githubusercontent.com/7587383/135768237-8c085ac5-c0bb-42cd-8615-3802eb0b6e74.png)
</details>

Здесь с первого взгляда невозможно разобраться в том, какие компоненты задействованы, какие у них настройки и т.д.
На проверку оказывается, что хоть ты и вызываешь здесь
```js
    $$("datapageCountries").parse(countries);
````
Глобальная (что само по себе нехорошо) айдишка `datapageCountries` находится даже не в импортированном `Datapage/Datapage_View.js `, а ещё дальше, в  `Datapage/Datapage_Countries.js`
Таким образом, там, где ты прописываешь конфигурацию multiview, ты почему-то вызываешь методы таблиц.

JetView нужны в том числе для того, чтобы держать там и конфигурацию, и логику доступной, насколько это возможно.
Поэтому требуется
- избавиться от лишнего вынесения объектов из конфига
- объединить связанные между собой компоненты в одном JetView (таблица+форма для Statuses и Countries) 
- перейти на локальные айдишки в классах

Т.е. 
```js
config() {
   return { rows: [
       { /* form */ },
       { localId: "table", /* config */ },
   ]},
   init(){
       this.$$("table").parse( /* some data */ )
   }
}

2021-10-03 19:46 UTC, HelgaListopad commented on sources/views/settings.js
> +      multiview: true,
Этот контрол не должен быть привязан ни к какому мультивью

2021-10-03 19:51 UTC, HelgaListopad commented
И если ты используешь не просто переменные, а методы, которые возвращают объекты, грамотнее было бы начинать название с `Get`: `GetDatapageCountriesConfig()`
Но это уже замечание скорее на будущее, см. мой большой комментарий по поводу необходимых здесь изменений.

2021-10-03 20:30 UTC, AlexeyXB commented
Полностью согласен с Олей. 
В дополнение к этому пару слов о работе самого приложения:

- в задании сказано про добавление, удаление и обновление элементов в таблицах на вкладке `Data`. Похоже, что обновление не работает. 
- после добавления новой записи, в инпутах остается введенное значение

2021-10-04 17:25 UTC, GlebMakhankov commented on sources/views/settings.js
> +      multiview: true,
Удалил компоненты-функции, кодстайл вроде поправил, глобальные ID заменил

2021-10-04 17:25 UTC, AlexeyXB approved these changes

2021-10-04 19:15 UTC, HelgaListopad approved these changes

2021-10-04 19:16 UTC, merged