Task 2
GlebMakhankov/webix-jet pull request #2
Opened 2021-10-05 15:33 UTC by GlebMakhankov

2021-10-05 15:50 UTC, AlexeyXB requested changes

2021-10-05 15:50 UTC, AlexeyXB commented on sources/components/contactsForm.js
> +								Storage.contacts.updateItem(entry.id, entry);
Если выбрать в листе кого-нибудь, потом нажать на `Clear`, потом заполнить форму и нажать на `Save`, будет ошибка. `Invalid ID for updateItem`

2021-10-05 15:50 UTC, AlexeyXB commented on sources/components/contactsForm.js
> +			elements: [
У элементов не хватает локализации

2021-10-05 15:50 UTC, AlexeyXB commented on sources/components/contactsForm.js
> +						: webix.message("<strong>No</strong> attached event"),
Для webix.message не хватает локализации

2021-10-05 15:50 UTC, AlexeyXB commented on sources/components/countries.js
> +							title: "Delete entry?",
Не хватает локализации

2021-10-05 15:50 UTC, AlexeyXB commented on sources/components/myCustomForm.js
> +							webix.message(
Для webix.message не хватает локализации

2021-10-06 06:31 UTC, AlexeyXB approved these changes

2021-10-06 07:22 UTC, HelgaListopad requested changes

2021-10-06 07:22 UTC, HelgaListopad commented on sources/components/contactsForm.js
> +						createButton(_("Clear"), () => {
В дополнение к очистке формы, здесь стоит сбросить селект листа и параметр из URL
Полностью удалить параметр из URL можно через `show`

2021-10-06 07:22 UTC, HelgaListopad commented on sources/components/contactsForm.js
> +							form.clearValidation();
Здесь то же самое: если чистишь форму, вместе с ней нужно чистить селект и URL
В целом, ты мог бы вынести `clear`+`clearValidation`+сброс остального в какой-нибудь свой метод класса

2021-10-06 07:22 UTC, HelgaListopad commented on sources/views/contacts.js
> +							this.$$("contactsList").remove(id);
Если мы удаляем строку, на которой стоит селект, нужно очистить форму и параметр в URL
То же нужно сделать, если удаляется последняя строка в таблице

2021-10-06 07:22 UTC, HelgaListopad commented on sources/views/contacts.js
> +		const form = this.getSubView("form").getRoot();
Само по себе решение использовать именованное subview в целом норм, но чище было бы вызывать не сразу `getRoot`, а какой-то свой метод класса от `getSubView("form")`, чтобы вернуть всю логику по работе с компонентами в тот класс, где они заданы. Не забывай, что модули приложения должны быть по возможности отделены друг от друга 
Условно
```js
// here
this.getSubView("form").passValues(item);

// contactsForm.js
passValues(item) {
   if (item)
      this.$$("form").setValues(item);
}
```

В противном случае, стоит изменить layout в классе с формой - и придётся по нескольким файлам вносить изменения, чтобы всё продолжало работать.

2021-10-06 13:30 UTC, HelgaListopad requested changes

2021-10-06 13:30 UTC, HelgaListopad commented on sources/components/contactsForm.js
> +    this.getParentView().$$("contactsList").unselectAll();
Здесь то же, от чего я советовала избавиться, только уже использованное в другую сторону - не нужно в мудуле формы обращаться напрямую к листу

2021-10-06 13:30 UTC, HelgaListopad commented on sources/components/contactsForm.js
> +    this.getParentView().$$("contactsList").unselectAll();
Здесь хорошей практикой будет вызов app-level события, которое будет отслеживаться в parent view и очищать у себя селект в листе.
Show я бы тоже вызывала в обработчике этого события, а не здесь (имеется в виду строчка ниже)

2021-10-06 15:35 UTC, HelgaListopad approved these changes

2021-10-06 15:56 UTC, merged